name: suamusica_weather
description: Sua Musica Challenge by Bruno Brito
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  dio: ^5.4.0
  flutter_modular: ^5.0.3
  lottie: ^3.0.0
  permission_handler: ^11.3.0
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/lottie/
